Add Kinyarwanda to keycloak theme
one-acre-fund/keycloak-themes pull request #1
Opened 2021-11-04 13:44 UTC by jniweteto

2021-11-08 08:28 UTC, joshjabour approved these changes
Looks good, and works well.

Noting the last few steps for this ticket:
1. Attempt to fix the configuration page (always reverts languages shown when rw is added)
2. Load to QA and test with Front end template
3. Demo for Sixbert and get feedback

2021-11-15 09:05 UTC, joshjabour requested changes
1 minor change requested. Otherwise looks and works great!

2021-11-15 09:05 UTC, joshjabour commented on themes/oaf/login/login.ftl
> +                                    <div id="kc-locale-wrapper" class="${properties.kcLocaleWrapperClass!} whitney-font-400"">
Delete extra double quote
```suggestion
                                    <div id="kc-locale-wrapper" class="${properties.kcLocaleWrapperClass!} whitney-font-400">
```

2021-11-15 11:14 UTC, joshjabour approved these changes
Looks good to me!

2021-11-30 08:54 UTC, bisonlou approved these changes

2021-11-30 09:37 UTC, merged